// layouts/header.vue
<template>
  <main class="flex flex-col lg:min-h-screen">
    <header class="bg-white flex flex-auto flex-col" style="height: 450px">
      <Navbar />
      <div class="container mx-auto py-4 flex flex-col items-center justify-center flex-auto h-full px-8">
        <div class="flex justify-center flex-col">
          <h1 class="text-3xl font-black text-indigo-900">
            <span class="text-4xl">Thomas</span><br />
            Développeur Web Front-end
          </h1>
          <p class="text-xl mt-4 text-gray-600 text-opacity-75 lg:w-1/2">
            Je suis développeur web et concepteur d'interfaces graphiques depuis maintenant 5 ans. Je prends beaucoup de plaisir à exercer cette passion.
          </p>
          <div class="container flex flex-row mt-4 space-x-8">
            <button class="flex justify-center bg-indigo-400 flex-initial w-44 py-2 rounded-md text-white focus:outline-none hover:bg-indigo-500">
              En découvrir plus
            </button>
            <button class="flex justify-center items-center text-indigo-400 hover:text-indigo-500">
              Me contacter
            </button>
          </div>
        </div>
      </div>
    </header>
    <section class="bg-indigo-400 pt-1 flex flex-col lg:flex-row lg:flex-grow-0">
      <article class="h-full bg-gray-200 lg:w-1/3">
        <img src="~/assets/entasia.png" class="pt-12 px-8 object-cover object-top h-full w-full"  alt=""/>
      </article>
      <article class="h-full bg-gray-50 lg:w-1/3">
        <img src="~/assets/palamazon.png" class="pt-12 px-8 object-cover object-top h-full w-full"  alt=""/>
      </article>
      <article class="h-full bg-gray-100 lg:w-1/3">
        <img src="~/assets/graphix.png" class="pt-12 px-8 object-cover object-top h-full w-full"  alt=""/>
      </article>
    </section>
  </main>
</template>

<script>
import Navbar from '~/layouts/navbar.vue';
export default {
  name: 'header',
  components: {
    Navbar,
  }
}
</script>

<style>
@media (min-width: 1024px) {
  section {
    height: 340px !important;
  }
}
</style>

// src/main/Header.jsx
import { IconArrowNarrowRight } from '@tabler/icons';
import Button from 'components/Button';

export default function App() {
  return <header className="relative min-h-screen overflow-hidden flex items-center justify-center">
    {/* Grid effect */}
    <div className="absolute w-full h-full grid-effect opacity-70"></div>
    {/* Bottom blur effect */}
    <div className="absolute -bottom-96 sm:-bottom-1/3 -left-1/3 -right-1/3 h-[35rem] bg-white blur-[3rem] sm:blur-[7rem] filter z-10"></div>

    {/* Centered header container */}
    <div className="text-center px-8 z-10 children:bg-white children:mx-auto">
      <img className="w-32 h-32 object-cover rounded-full mx-auto shadow-md" src="https://cdn.discordapp.com/attachments/768087687655194675/949965497301106729/66BB0FC6-BA56-46CF-83BD-1305865FEBB8.jpg" alt="" />

      <h1 className="font-black text-6xl text-black pt-4">
        thomas vergne
      </h1>
      <p className="text-xl pt-2 pb-10 px-8 text-black text-opacity-60">
        Concepteur et développeur de langages de programmation
      </p>
      <Button black withIcon={IconArrowNarrowRight}>
        Découvrir mes travaux
      </Button>
    </div>
  </header>
}
