// components/Navbar.jsx
import { IconBrandTwitter } from '@tabler/icons';
import { IconBrandGithub } from '@tabler/icons';
import { Link } from 'react-router-dom';

export default function Navigation() {
  return <nav className="container mx-auto p-8 md:pt-8 flex flex-col md:flex-row items-center 2xl:w-4/5">
    <div className="flex flex-initial flex-col md:flex-row items-center text-center md:text-left">
      <img className="w-20 h-20 object-cover rounded-full shadow-md" src="https://cdn.discordapp.com/attachments/768087687655194675/949965497301106729/66BB0FC6-BA56-46CF-83BD-1305865FEBB8.jpg" alt="" />
      <div className="flex flex-col md:ml-4 justify-center">
        <h1 className="font-black text-2xl text-black">
          thomas vergne
        </h1>
        <Link to="/" className="text-lg -mt-1 text-neutral-500 hover:underline underline-offset-1">
          Retourner à la page d'accueil
        </Link>
      </div>
    </div>
    <div className="flex flex-auto mt-8 md:mt-0 justify-end">
      <ul className="flex gap-x-8 children:text-5xl">
        <IconBrandGithub size={30} />
        <IconBrandTwitter size={30} />
      </ul>
    </div>
  </nav>;
}

// src/components/navbar.svelte
<script>
  import Logo from '../assets/logo.png';
</script>

<nav class="p-4 lg:p-8 lg:px-0">
    <div class="flex flex-row lg:justify-center lg:w-2/3 lg:mx-auto">
        <div class="container flex-row flex flex-initial w-32 lg:justify-center">
            <img src={Logo} class="rounded-full w-16 h-16 shadow-lg" alt="Thomas's logo" />
        </div>
        <div class="container flex flex-col flex-auto mt-4 lg:mt-0 lg:flex-row px-4 lg:pr-6">
            <span class="items-center flex text-2xl font-semibold text-gray-800">
                Thomas Vergne
            </span>
            <ul class="flex flex-col py-4 space-y-1 text-gray-500 lg:flex-row lg:space-y-0 lg:py-0 lg:items-center lg:justify-end lg:flex-auto lg:space-x-6">
                <li class="hover:text-gray-700 cursor-pointer">
                    Présentation
                </li>
                <li class="hover:text-gray-700 cursor-pointer">
                    Domaines et compétences
                </li>
                <li class="hover:text-gray-700 cursor-pointer">
                    Projets
                </li>
            </ul>
        </div>
        <div class="container flex flex-row justify-end px-4 flex-initial w-1/4 lg:w-32 lg:px-0 lg:px-0 lg:justify-center">
            <ul class="flex mt-5 lg:mt-0 lg:items-center text-2xl text-gray-800 space-x-5">
                <i class="fab fa-github"></i>
                <i class="fab fa-twitter text-blue-400"></i>
            </ul>
        </div>
    </div>
</nav>
